### ISSUE TITLE
Create npm package

### ISSUE THREAD

**Issue by diegomura** [devongovett/textkit#16]
@devongovett I think we are close on releasing the first (beta) version to npm.
My goal is to integrate this into react-pdf eventually, so I'll need this. This would also work as a good use case for this library in order to test it action.
As you own the project, I would suggest that you should create the package. It would be cool if I can be granted for publishing, at least for awhile until I have this working inside react-pdf 😄

**Comment by devongovett** [comment]
Awesome. In order to do this, we'll need to also release the changes to fontkit and pdfkit that this depends on. That might take some more time as those projects are actually used in production. If you want to help clean up the code for those branches, that would be awesome. I think the pdfkit one is much more messy and will definitely break current usages (we need it to be backward compatibile).

**Comment by diegomura** [comment]
Thanks @devongovett . 
I understand that. I would be more than happy to help. Could you give me some hints on how to start fixing these particular branches?

It seems to me that both branches adds new features: for pdfkit, adds a new method fo adding glyphs straight to the document, and for fontkit makes it return the string indices. Pdfkit branch has conflicts, so I guess we will need to fix those, but besides from that, is there anything else needed?

Thanks in advance!

**Comment by diegomura** [comment]
@devongovett I worked a bit on the `textkit` branch on `pdfkit` today. I submitted a PR (https://github.com/devongovett/pdfkit/pull/798) in which I explained what I tried to do. I would really appreciate if you can take a look 😄 Thanks!
